language: python
python:
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly"
# command to install dependencies
addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - gfortran
      - libatlas-base-dev
install:
  - pip install unittest2
  - pip install h5py
  - travis_wait 30 pip install scipy
cache: pip
# command to run tests
script: python setup.py test
