language: python
jobs:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: osx
      language: generic
      env: PYTHON=3.7.4
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi
install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_retry pip install numpy; fi
  - travis_retry pip install tox tox-travis
  - if [ ! "$(ls -A tests/data)" ]; then curl -L https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20190812.tar.gz -o xu_testdata.tar.gz && tar xzf xu_testdata.tar.gz -C tests; fi
cache:
  pip: true
  directories:
   - tests/data
script: tox
