language: python
sudo: true
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - travis_retry pip install tox
  - if [ ! "$(ls -A tests/data)" ]; then wget https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20190812.tar.gz -O xu_testdata.tar.gz && tar xzf xu_testdata.tar.gz -C tests; fi
cache:
  pip: true
  directories:
   - tests/data
# command to run tests
script: tox
