language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# command to install dependencies
install:
  - pip install --user numpy scipy h5py
# command to run tests
script: python setup.py test
