language: python
jobs:
  include:
    - os: linux
      python: 3.6
      env: TOX_TESTENV_PASSENV=CI
    - os: linux
      python: 3.7
      env: TOX_TESTENV_PASSENV=CI
    - os: linux
      python: 3.8
    - os: osx
      language: generic
      env:
        - PYENV_VERSION=3.8.5
        - PYENV_VERSION_STRING='Python 3.8.5'
        - TOXENV=py38
        - TOX_TESTENV_PASSENV=CI
    - os: windows
      language: shell
      env:
        - TOXENV=py38
        - TOX_TESTENV_PASSENV=CI
        - PYTHON=3.8.5
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
  allow_failures:
    - os: windows
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    if [[ -n "$PYENV_VERSION" ]]; then
        wget https://github.com/praekeltfoundation/travis-pyenv/releases/download/0.4.0/setup-pyenv.sh
        source setup-pyenv.sh
    fi
  elif [ "$TRAVIS_OS_NAME" == "windows" ]; then
    choco install python --version $PYTHON
    python -m pip install --upgrade pip
  fi
install:
  - env
  - python3 --version || python --version
  - travis_retry pip3 install tox tox-travis tox-wheel
  - |
    if [ ! "$(ls -A tests/data)" ]; then
      travis_wait curl -s -L https://sourceforge.net/projects/xrayutilities/files/xrayutilities-testdata-20190812.tar.gz -o xu_testdata.tar.gz
      tar xzf xu_testdata.tar.gz -C tests
    fi
cache:
  pip: true
  directories:
   - tests/data
   - $HOME/.pyenv_cache
script:
  - travis_wait 30 tox
