environment:
  TOX_TESTENV_PASSENV: "*"
  PYTHON: C:\Python38-x64
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXENV: py36
      TOX_APPVEYOR_X64: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXENV: py36
      TOX_APPVEYOR_X64: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXENV: py37
      TOX_APPVEYOR_X64: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXENV: py37
      TOX_APPVEYOR_X64: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXENV: py38
      TOX_APPVEYOR_X64: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      TOXENV: py38
      TOX_APPVEYOR_X64: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      PYVER: 3.8
      TOXENV: py38

#stack: python %PYVER%

install:
  - ps: |
      $env:package_version=(Get-Content -Path lib/xrayutilities/VERSION)
      Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
      if ($isWindows) {
        $env:Path="$env:PYTHON;$env:PYTHON\Scripts;$env:Path"
        [Environment]::SetEnvironmentVariable("Path", "$env:PYTHON;$env:PYTHON\Scripts;senv:Path", [EnvironmentVariableTarget]::User)
      }
      if ($isLinux) {
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        sudo apt update
        sudo apt -y install python3-pip
      }
      python -m pip install --upgrade --ignore-installed pip
      python -m pip install numpy tox tox-wheel tox-appveyor

build: off

test_script:
  - python -m tox

artifacts:
  - path: dist\*
