image:
  - Ubuntu2004
  - Visual Studio 2019

environment:
  TOX_TESTENV_PASSENV: "*"
  matrix:
#    - PYTHON: C:\Python36-x64
#      PYVER: 3.6
#      TOXENV: py36
#    - PYTHON: C:\Python37-x64
#      PYVER: 3.7
#      TOXENV: py37
    - PYTHON: C:\Python38-x64
      PYVER: 3.8
      TOXENV: py38

#stack: python %PYVER%

install:
  - ps: |
      $env:package_version=(Get-Content -Path lib/xrayutilities/VERSION)
      Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
      if ($isWindows) {
        $env:Path="$env:PYTHON;$env:PYTHON\Scripts;$env:Path"
        [Environment]::SetEnvironmentVariable("Path", "$env:PYTHON;$env:PYTHON\Scripts;senv:Path", [EnvironmentVariableTarget]::User)
      }
      if ($isLinux) {
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
        sudo apt update
        sudo apt -y install python3-pip
      }
      python -m pip install --upgrade --ignore-installed pip
      python -m pip install numpy tox tox-wheel

build: off

test_script:
  - python -m tox

artifacts:
  - path: dist\*
